// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Srceen_AIoT_PTIT

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen_QR = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Screen_QR, &ui_img_screen_qr_png);
    lv_obj_set_width(ui_Screen_QR, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Screen_QR, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Screen_QR, 0);
    lv_obj_set_y(ui_Screen_QR, -2);
    lv_obj_set_align(ui_Screen_QR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_QR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen_QR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
