// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Srceen_AIoT_PTIT

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen3, &ui_img_screen_temp_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -75);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "AIoT PTIT");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMP = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_TEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMP, -75);
    lv_obj_set_y(ui_TEMP, -13);
    lv_obj_set_align(ui_TEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMP, "29");
    lv_obj_set_style_text_font(ui_TEMP, &ui_font_Oswald_Regular_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -41);
    lv_obj_set_y(ui_Label4, -20);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "°");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -20);
    lv_obj_set_y(ui_Label5, -22);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "C");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_SFMono_Bold_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 6);
    lv_obj_set_y(ui_Label6, -15);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "|");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HUMI = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_HUMI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HUMI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HUMI, 48);
    lv_obj_set_y(ui_HUMI, -12);
    lv_obj_set_align(ui_HUMI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HUMI, "80");
    lv_obj_set_style_text_font(ui_HUMI, &ui_font_Oswald_Regular_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 89);
    lv_obj_set_y(ui_Label8, -19);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "%");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Oswald_Regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 219);
    lv_obj_set_y(ui_Label12, 5);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "0");

    ui_Label13 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 206);
    lv_obj_set_y(ui_Label13, -2);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);

}
