// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Srceen_AIoT_PTIT

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_screen_clock_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 200, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Day = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Day, -50);
    lv_obj_set_y(ui_Day, -61);
    lv_obj_set_align(ui_Day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Day, "SUN");
    lv_obj_set_style_text_color(ui_Day, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Day, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 1);
    lv_obj_set_y(ui_Date, -61);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "30");
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_month, 52);
    lv_obj_set_y(ui_month, -61);
    lv_obj_set_align(ui_month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month, "JUN");
    lv_obj_set_style_text_font(ui_month, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour_1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_hour_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour_1, -86);
    lv_obj_set_y(ui_hour_1, 3);
    lv_obj_set_align(ui_hour_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour_1, "0");
    lv_obj_set_style_text_font(ui_hour_1, &ui_font_Roboto_Bold_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour_2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_hour_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour_2, -39);
    lv_obj_set_y(ui_hour_2, 3);
    lv_obj_set_align(ui_hour_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour_2, "5");
    lv_obj_set_style_text_font(ui_hour_2, &ui_font_Roboto_Bold_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 1);
    lv_obj_set_y(ui_Label16, -3);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, ":");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Roboto_Bold_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute_1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_minute_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute_1, 41);
    lv_obj_set_y(ui_minute_1, 3);
    lv_obj_set_align(ui_minute_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute_1, "0");
    lv_obj_set_style_text_font(ui_minute_1, &ui_font_Roboto_Bold_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute_2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_minute_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute_2, 88);
    lv_obj_set_y(ui_minute_2, 2);
    lv_obj_set_align(ui_minute_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute_2, "0");
    lv_obj_set_style_text_font(ui_minute_2, &ui_font_Roboto_Bold_80, LV_PART_MAIN | LV_STATE_DEFAULT);

}
